title: Learner's Guide
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dafuzhu-uchi.github.io/learn

plugins:
  - jekyll-default-layout